
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author damA
 */
public class BuscarporSala extends javax.swing.JDialog {
Conectar conectar=null;
    /**
     * Creates new form BuscarporSala
     */
    public BuscarporSala(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         conectar = new Conectar();
        añdircombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxSala = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBoxSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jComboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jComboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSalaActionPerformed
        // TODO add your handling code here:
        int  id= jComboBoxSala.getSelectedIndex()+1;
        String sql = "select titulo from cine_di.pelicula where\n" +
        "sala in (select idSala from  cine_di.sala where idSala = \""+id+"\");";
        DefaultTableModel dtm = new  DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Titulo"});
        Statement ps =null;
        Connection cn = conectar.getConnection();
        ResultSet rs = null;
        try {
            ps= cn.prepareStatement(sql);
            rs=ps.executeQuery(sql);

            while(rs.next())
            {
                String[] total = new String[8];
                total[0]= rs.getString("titulo").toString();
                dtm.addRow(total);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jTable1.setModel(dtm);
    }//GEN-LAST:event_jComboBoxSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void añdircombo() {
         String sql = "select nombre from cine_di.sala;";
        Statement ps = null;
        ResultSet rs = null;
        
        Connection cn = conectar.getConnection();
        
        try {
            ps= cn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
            while (rs.next()) {
                 jComboBoxSala.addItem(rs.getString("nombre").toString());
            }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSala;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
