
import java.sql.Connection;
import java.sql.JDBCType;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cesar
 */
public class MostrarPorDirector extends javax.swing.JDialog {
Conectar conectar= null;
    /**
     * Creates new form MostrarPorDirector
     */
    public MostrarPorDirector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conectar = new Conectar();
        añdircombo();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxDirector = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDirectorActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jComboBoxDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jComboBoxDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDirectorActionPerformed
        // TODO add your handling code here:
        int  id= jComboBoxDirector.getSelectedIndex()+1;
        String sql = "select titulo from cine_di.pelicula where\n" +
        "director in (select idDirector from  cine_di.director where idDirector = \""+id+"\");";
        DefaultTableModel dtm = new  DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Titulo"});
        Statement ps =null;
        Connection cn = conectar.getConnection();
        ResultSet rs = null;
        try {
             ps= cn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
            
            while(rs.next())
            {
            String[] total = new String[8];
            total[0]= rs.getString("titulo").toString();
            dtm.addRow(total);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       jTable1.setModel(dtm);
    }//GEN-LAST:event_jComboBoxDirectorActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxDirector;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void añdircombo() {
       String sql = "select nombre, apellidos from cine_di.director;";
        Statement ps = null;
        ResultSet rs = null;
        
        Connection cn = conectar.getConnection();
        
        try {
            ps= cn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
            while (rs.next()) {
                 jComboBoxDirector.addItem(rs.getString("nombre").toString()+" "+rs.getString("apellidos").toString());
            }
        } catch (Exception e) {
        }
        
      
    }
}
